language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  - DEPS="numpy scipy nose"

install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes $DEPS
  - python setup.py install

before_install:
  # then install python version to test
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-2.2.2-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # miniconda is not always up-to-date with conda.
  - conda update --yes conda

script:
  - nosetests supersmoother
